name: Testing app

on: 
  push:
  branches[ master ]
#   pull_request:
#   branches[ main ]

# auto runnig workflow is here...
jobs:
  # This workflow contains single job called build...
  build:
    # the type of runner that the job will run on...
    runs-on: ubuntu-latest
    
    steps:
    # checkout repo under github, so your job can access it...
    - uses: action/checkout@v2
    
    - name: Installing node..
      run: actions/setup-node@v2-beta
      with:
        node-version: 12  
      
    - name: installing surge
      run: npm install --global surge
      
    - name: deploying using surge
      # add token of surge in secrets in setting of git hub project.
      # running cmd: surge PATH LINK_LIVE-URL --token $ {{add token from git secrets}}
      run: surge ./ learningandtesting.surge.sh --token $ {{secrets.SURGE_TOKEN}}
      
      
    
    
    
